[project]
name = "my-grpc-project"
version = "0.1.0"
description = "Simple gRPC example using uv"
dependencies = [
    "grpcio",
    "grpcio-tools",
    "black",
    "ruff",
    "mypy",
    "pytest",
    "types-protobuf>=6.30.2.20250516",
    "requests>=2.32.4",
    "async-timeout>=5.0.1",
    "cython>=3.1.2",
    "fastapi>=0.115.12",
    "aio-pika>=9.5.5",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

