# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common.proto.scheduler_callback_pb2 as scheduler__callback__pb2

GRPC_GENERATED_VERSION = "1.72.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in scheduler_callback_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleCallback = channel.unary_unary(
            "/Scheduler/ScheduleCallback",
            request_serializer=scheduler__callback__pb2.ScheduleRequest.SerializeToString,
            response_deserializer=scheduler__callback__pb2.ScheduleResponse.FromString,
            _registered_method=True,
        )


class SchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScheduleCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ScheduleCallback": grpc.unary_unary_rpc_method_handler(
            servicer.ScheduleCallback,
            request_deserializer=scheduler__callback__pb2.ScheduleRequest.FromString,
            response_serializer=scheduler__callback__pb2.ScheduleResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Scheduler", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("Scheduler", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScheduleCallback(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Scheduler/ScheduleCallback",
            scheduler__callback__pb2.ScheduleRequest.SerializeToString,
            scheduler__callback__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
