# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler_callback.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 0, "", "scheduler_callback.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18scheduler_callback.proto"A\n\x0fScheduleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0curl_callback\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x05""\n\x10ScheduleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2D\n\tScheduler\x12\x37\n\x10ScheduleCallback\x12\x10.ScheduleRequest\x1a\x11.ScheduleResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "scheduler_callback_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SCHEDULEREQUEST"]._serialized_start = 28
    _globals["_SCHEDULEREQUEST"]._serialized_end = 93
    _globals["_SCHEDULERESPONSE"]._serialized_start = 95
    _globals["_SCHEDULERESPONSE"]._serialized_end = 129
    _globals["_SCHEDULER"]._serialized_start = 131
    _globals["_SCHEDULER"]._serialized_end = 199
# @@protoc_insertion_point(module_scope)
